---
- name: webserver-audit
  box: trombik/ansible-centos-7.3-x86_64
  hostname: webserver
  ipaddress: 172.16.0.11
  memory: 2048
  cpus: 1
  provision: provision/ansible/webserver.yaml

- name: graylog-audit
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: graylog
  ipaddress: 172.16.0.12
  memory: 2560
  cpus: 1
  provision: provision/ansible/graylog.yaml

- name: kibana-audit
  box: darkwizard242/ansibledebian10
  hostname: kibana
  ipaddress: 172.16.0.13
  memory: 2560
  cpus: 1
  provision: provision/ansible/kibana.yaml
